version: '3.8'

services:
  redis-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-microservice
    restart: always
    env_file:
      - .env
    networks:
      - elastika-network
    volumes:
      - ./logs:/app/logs
    ports:
      - "3003:3003"

networks:
  elastika-network:
    external: true